version: "3.9"
services:
  postgres:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6
    volumes:
      - ./tmp/db:/var/lib/redis/data
    command: redis-server
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mycontentful
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env'